import { Schema } from "effect"

export const ObsRequestType = Schema.Literal(
  "GetVersion",
  "GetStats",
  "GetHotkeyList",
  "TriggerHotkeyByName",
  "TriggerHotkeyByKeySequence",
  "GetCanvasList",
  "GetTransitionKindList",
  "GetSceneTransitionList",
  "GetCurrentSceneTransition",
  "GetCurrentSceneTransitionCursor",
  "SetCurrentSceneTransition",
  "SetCurrentSceneTransitionDuration",
  "SetCurrentSceneTransitionSettings",
  "TriggerStudioModeTransition",
  "SetTBarPosition",
  "GetSceneList",
  "GetCurrentProgramScene",
  "SetCurrentProgramScene",
  "GetSceneItemList",
  "GetGroupSceneItemList",
  "GetSceneItemId",
  "GetSceneItemSource",
  "GetSceneItemEnabled",
  "SetSceneItemEnabled",
  "GetSceneItemLocked",
  "SetSceneItemLocked",
  "GetSceneItemIndex",
  "GetSceneItemBlendMode",
  "SetSceneItemIndex",
  "SetSceneItemBlendMode",
  "GetSourceActive",
  "GetInputList",
  "GetInputKindList",
  "GetSpecialInputs",
  "GetInputMute",
  "SetInputMute",
  "ToggleInputMute",
  "GetInputVolume",
  "SetInputVolume",
  "GetInputAudioBalance",
  "SetInputAudioBalance",
  "GetInputAudioMonitorType",
  "SetInputAudioMonitorType",
  "GetInputAudioSyncOffset",
  "SetInputAudioSyncOffset",
  "GetMediaInputStatus",
  "SetMediaInputCursor",
  "OffsetMediaInputCursor",
  "TriggerMediaInputAction",
  "GetVirtualCamStatus",
  "StartVirtualCam",
  "StopVirtualCam",
  "ToggleVirtualCam",
  "GetReplayBufferStatus",
  "StartReplayBuffer",
  "StopReplayBuffer",
  "ToggleReplayBuffer",
  "SaveReplayBuffer",
  "GetLastReplayBufferReplay",
  "GetRecordStatus",
  "StartRecord",
  "StopRecord",
  "ToggleRecord",
  "SplitRecordFile",
  "CreateRecordChapter",
  "PauseRecord",
  "ResumeRecord",
  "ToggleRecordPause",
  "GetStreamStatus",
  "StartStream",
  "StopStream",
  "ToggleStream",
  "SendStreamCaption",
  "GetStudioModeEnabled"
)
export type ObsRequestType = typeof ObsRequestType.Type

export * from "./requests/canvases.js"
export * from "./requests/general.js"
export * from "./requests/inputs.js"
export * from "./requests/outputs.js"
export * from "./requests/record.js"
export * from "./requests/scenes.js"
export type { ObsRequestDescriptor } from "./requests/shared.js"
export * from "./requests/stream.js"
export * from "./requests/transitions.js"
export * from "./requests/ui.js"
