import { Schema } from "effect"

export const OBS_REQUEST_TYPES = [
  "GetVersion",
  "GetStats",
  "GetHotkeyList",
  "TriggerHotkeyByName",
  "TriggerHotkeyByKeySequence",
  "GetProfileList",
  "GetSceneCollectionList",
  "GetProfileParameter",
  "GetRecordDirectory",
  "SetRecordDirectory",
  "GetVideoSettings",
  "SetVideoSettings",
  "GetStreamServiceSettings",
  "SetStreamServiceSettings",
  "SetCurrentProfile",
  "CreateProfile",
  "RemoveProfile",
  "SetCurrentSceneCollection",
  "CreateSceneCollection",
  "SetProfileParameter",
  "GetCanvasList",
  "GetTransitionKindList",
  "GetSceneTransitionList",
  "GetCurrentSceneTransition",
  "GetCurrentSceneTransitionCursor",
  "SetCurrentSceneTransition",
  "SetCurrentSceneTransitionDuration",
  "SetCurrentSceneTransitionSettings",
  "TriggerStudioModeTransition",
  "SetTBarPosition",
  "GetSceneList",
  "GetGroupList",
  "GetCurrentProgramScene",
  "GetCurrentPreviewScene",
  "SetCurrentProgramScene",
  "SetCurrentPreviewScene",
  "CreateScene",
  "RemoveScene",
  "SetSceneName",
  "GetSceneSceneTransitionOverride",
  "SetSceneSceneTransitionOverride",
  "GetSceneItemList",
  "GetGroupSceneItemList",
  "CreateSceneItem",
  "RemoveSceneItem",
  "DuplicateSceneItem",
  "GetSceneItemId",
  "GetSceneItemSource",
  "GetSceneItemTransform",
  "SetSceneItemTransform",
  "GetSceneItemEnabled",
  "SetSceneItemEnabled",
  "GetSceneItemLocked",
  "SetSceneItemLocked",
  "GetSceneItemIndex",
  "GetSceneItemBlendMode",
  "SetSceneItemIndex",
  "SetSceneItemBlendMode",
  "GetSourceActive",
  "GetSourceScreenshot",
  "SaveSourceScreenshot",
  "GetSourceFilterKindList",
  "GetSourceFilterList",
  "GetSourceFilterDefaultSettings",
  "GetSourceFilter",
  "CreateSourceFilter",
  "RemoveSourceFilter",
  "SetSourceFilterSettings",
  "SetSourceFilterEnabled",
  "SetSourceFilterIndex",
  "SetSourceFilterName",
  "GetInputList",
  "GetInputKindList",
  "GetSpecialInputs",
  "GetInputMute",
  "SetInputMute",
  "ToggleInputMute",
  "GetInputVolume",
  "SetInputVolume",
  "GetInputAudioBalance",
  "SetInputAudioBalance",
  "GetInputAudioMonitorType",
  "SetInputAudioMonitorType",
  "GetInputAudioSyncOffset",
  "SetInputAudioSyncOffset",
  "GetInputAudioTracks",
  "SetInputAudioTracks",
  "GetInputDeinterlaceMode",
  "SetInputDeinterlaceMode",
  "GetInputDeinterlaceFieldOrder",
  "SetInputDeinterlaceFieldOrder",
  "GetInputDefaultSettings",
  "GetInputSettings",
  "GetInputPropertiesListPropertyItems",
  "SetInputSettings",
  "PressInputPropertiesButton",
  "CreateInput",
  "RemoveInput",
  "SetInputName",
  "GetMediaInputStatus",
  "SetMediaInputCursor",
  "OffsetMediaInputCursor",
  "TriggerMediaInputAction",
  "GetVirtualCamStatus",
  "GetOutputList",
  "GetOutputStatus",
  "GetOutputSettings",
  "SetOutputSettings",
  "StartOutput",
  "StopOutput",
  "ToggleOutput",
  "StartVirtualCam",
  "StopVirtualCam",
  "ToggleVirtualCam",
  "GetReplayBufferStatus",
  "StartReplayBuffer",
  "StopReplayBuffer",
  "ToggleReplayBuffer",
  "SaveReplayBuffer",
  "GetLastReplayBufferReplay",
  "GetRecordStatus",
  "StartRecord",
  "StopRecord",
  "ToggleRecord",
  "SplitRecordFile",
  "CreateRecordChapter",
  "PauseRecord",
  "ResumeRecord",
  "ToggleRecordPause",
  "GetStreamStatus",
  "StartStream",
  "StopStream",
  "ToggleStream",
  "SendStreamCaption",
  "GetStudioModeEnabled",
  "SetStudioModeEnabled",
  "OpenInputPropertiesDialog",
  "OpenInputFiltersDialog",
  "OpenInputInteractDialog",
  "GetMonitorList",
  "OpenVideoMixProjector",
  "OpenSourceProjector",
  "GetPersistentData",
  "SetPersistentData",
  "CallVendorRequest",
  "BroadcastCustomEvent",
  "Sleep"
] as const

export const ObsRequestType = Schema.Literal(...OBS_REQUEST_TYPES)
export type ObsRequestType = typeof ObsRequestType.Type

export * from "./requests/canvases.js"
export * from "./requests/config.js"
export * from "./requests/filters.js"
export * from "./requests/general.js"
export * from "./requests/inputs.js"
export * from "./requests/outputs.js"
export * from "./requests/persistent-data.js"
export * from "./requests/record.js"
export * from "./requests/scenes.js"
export * from "./requests/screenshots.js"
export type { ObsRequestDescriptor } from "./requests/shared.js"
export * from "./requests/stream.js"
export * from "./requests/transitions.js"
export * from "./requests/ui.js"
export * from "./requests/vendor.js"
